#!/usr/bin/env python3
"""The shape channel: square or circle, laid over the triple from in-use.tsv.

`mark(rgb, grid)` is the entry point; `python3 shaped.py` runs the selftest.

Order alone cannot separate every colour: ordered triples of nine colours reach
729 and the gamut is 1074. Shape is not a weak tiebreak — it is preattentive,
and a circle among squares is found without search.

**Black and white stay square.** Unicode names their circles MEDIUM BLACK CIRCLE
and MEDIUM WHITE CIRCLE where every palette square is LARGE, and the palette is
anchored on those names — the size word is part of the definition, not a
rendering detail. A MEDIUM neutral among LARGE chromatics reads ragged, and
white alone lands on 53 colours. Justin's direction, 2026-08-19.

That leaves seven circleable colours and two that are not, so a position offers
sixteen glyphs rather than eighteen, and ordered marks reach 4096 against the
gamut's 1074 — where colour and order together fell short by 345.

Both channels are drawn mixed-radix from `grid_bits(grid)`, fifteen bits of the
key's digest and a slice disjoint from the one the hue is drawn from. `arrange`
takes the remainder against the permutation count; shape takes the quotient. So
arrangement is bit-for-bit unchanged (sheets 4 and 5 differ only in shape), and
the two draws stay independent — reducing one number mod 6 and again mod 8
would correlate them.
"""

import bisect
import importlib.util
import itertools
import pathlib

# ---- The modules this is layered over ----

S = pathlib.Path(__file__).resolve().parent
D = str(S.parent) + "/"


def load(path, module):
    spec = importlib.util.spec_from_file_location(module, path)
    loaded = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(loaded)
    return loaded


text = load(D + "text-identicon.py", "t")
wheel = load(str(S / "wheel.py"), "wheel")

# ---- The arc table ----

# `in-use.tsv` is the mapping, generated by `wheel.py --reference` from
# `wheel.tsv` -- edit the source, not this. The shape channel is laid over
# whatever it says, so the two cannot fall out of step.
# columns: from  to  n  one  two  three  mark
_ARCS = []
for _line in (S / "in-use.tsv").read_text().splitlines():
    if _line.startswith("#") or not _line.strip():
        continue
    _f = _line.split("\t")
    # Through the palette and back, so an unknown name raises here rather than
    # drawing the wrong square. The names tuple is shared by every lookup;
    # `arrange` does not mutate its argument.
    _ARCS.append((float(_f[0]), float(_f[1]),
                  tuple(text.PALETTE[wheel.ORDER[n]][1] for n in _f[3:6])))
# `from` is distinct on every row, so this never compares the name tuples.
_ARCS.sort()
_STARTS = [a[0] for a in _ARCS]


# ---- Choosing the mark ----


def draw_of(rgb):
    """Where in the draw this colour came from, recovered from the colour alone.

    **The table is indexed by the draw, not by the hue.** Mapping version 3
    warps the draw before using it as a hue, so a plain HSL hue here is wrong by
    up to a third of the wheel around the blue-greens -- the mistake the header
    of `in-use.tsv` warns about. The warp is monotonic so it inverts, and the
    hue is read in Oklab, the space the mark's colour was built in.

    A caller holding the key should pass its own draw to `mark` instead, which
    is exact. This is the colour-only path and carries the quantising error --
    see `_selftest`, which measures how often that lands in the wrong arc.
    """
    return wheel.warp_angle(wheel.hue_angle(rgb)) % 360.0


def triple(rgb, grid, draw=None):
    """The three palette indices for `rgb`, in laid-out order.

    Which three squares is a table lookup on the draw; what order they go in is
    `text.arrange` on the grid, whose docstring argues why.
    """
    at = draw_of(rgb) if draw is None else draw % 360.0
    _lo, _hi, names = _ARCS[bisect.bisect_right(_STARTS, at) - 1]
    return text.arrange(tuple(wheel.ORDER[n] for n in names), grid)


# ---- The glyph vocabulary ----
#
# `glyphs.py` lists the same nine squares and seven circles by codepoint; the
# two must stay in step.

# Never circled. See the module docstring: their circles are MEDIUM where every
# square is LARGE, and the Unicode name is the palette's definition.
ALWAYS_SQUARE = ("black", "white")

# The seven that can be either. Red and blue come from Unicode 6's emoji block
# and the rest from Unicode 12's, which is why the codepoints are not one run --
# the same split that puts the black and white squares at U+2B1B and U+2B1C
# rather than alongside their coloured siblings.
CIRCLES = {
    "red":    "\U0001F534",   # LARGE RED CIRCLE
    "orange": "\U0001F7E0",   # LARGE ORANGE CIRCLE
    "yellow": "\U0001F7E1",   # LARGE YELLOW CIRCLE
    "green":  "\U0001F7E2",   # LARGE GREEN CIRCLE
    "blue":   "\U0001F535",   # LARGE BLUE CIRCLE
    "purple": "\U0001F7E3",   # LARGE PURPLE CIRCLE
    "brown":  "\U0001F7E4",   # LARGE BROWN CIRCLE
}


def _arrangements(indices):
    """How many distinct orders the multiset affords -- 1, 3 or 6.

    Recomputed here rather than imported because it is the radix `arrange`
    consumed, and the shape channel must divide by exactly that to take the
    next digit rather than a correlated one.
    """
    return len(set(itertools.permutations(indices)))


def circleable(arranged):
    """Positions in the laid-out triple that may take a circle."""
    return [k for k, i in enumerate(arranged)
            if text.PALETTE[i][1] not in ALWAYS_SQUARE]


def shapes(arranged, grid):
    """Which of the three laid-out positions are circles.

    A tuple of three booleans, True meaning circle. All False when the triple
    holds nothing circleable, which is the black-and-white corner of the gamut.
    """
    positions = circleable(arranged)
    out = [False, False, False]
    if not positions:
        return tuple(out)
    # **The grid, not the colour.** Hashing `#rrggbb` made both channels
    # functions of an output of the mapping -- two projects on the same
    # quantised colour got the same order and the same circles, necessarily.
    # The grid is fifteen bits of the key's digest, from a slice disjoint from
    # the one the hue is drawn from.
    value = text.grid_bits(grid) // _arrangements(arranged)
    bits = value % (1 << len(positions))
    for j, position in enumerate(positions):
        out[position] = bool(bits >> j & 1)
    return tuple(out)


def mark(rgb, grid, draw=None):
    """`(arranged indices, shape flags)` -- the whole choice for one project."""
    arranged = triple(rgb, grid, draw)
    return arranged, shapes(arranged, grid)


# ---- Rendering a mark ----


def emoji(rgb, grid):
    """The three emoji for this project, shapes applied, as one string."""
    arranged, flags = mark(rgb, grid)
    out = []
    for index, circle in zip(arranged, flags):
        name = text.PALETTE[index][1]
        out.append(CIRCLES[name] if circle else text.PALETTE[index][0])
    return "".join(out)


def names(rgb, grid):
    """The three squares as `colour` or `colour-circle`, in laid-out order."""
    arranged, flags = mark(rgb, grid)
    return tuple(f"{text.PALETTE[i][1]}{'-circle' if c else ''}"
                 for i, c in zip(arranged, flags))


def key(rgb, grid):
    """A hashable identity for the whole mark, for spread measurement."""
    arranged, flags = mark(rgb, grid)
    return tuple(zip(arranged, flags))


# ---- Selftest ----


def _selftest():
    """**Measured over projects, not over colours.**

    A sweep of one sample per colour cannot see the fault this exists to catch:
    it makes every mark look distinct by construction, however many projects are
    piled on one colour. The population is projects, so the sample is projects.
    """
    identicon = load(D + "repository-identicon.py", "i")
    N = 4000
    rows = []
    for k in range(N):
        key_ = identicon.stamp_key(f"github.com/example/project-{k:05d}", 3)
        rows.append((identicon.identicon_colour(key_),
                     identicon.identicon_grid(key_),
                     identicon.identicon_hue(key_) * 360.0))

    for rgb, grid, draw in rows[:500]:
        assert mark(rgb, grid, draw) == mark(rgb, grid, draw)
        assert mark(rgb, grid, draw)[0] == triple(rgb, grid, draw)
        arranged, flags = mark(rgb, grid, draw)
        for index, circle in zip(arranged, flags):
            assert not (circle and text.PALETTE[index][1] in ALWAYS_SQUARE)
        assert len(emoji(rgb, grid)) == 3

    colours = len({text.hex_colour(r) for r, _g, _d in rows})
    triples = len({triple(r, g, d) for r, g, d in rows})
    marks = len({key(r, g) for r, g, _d in rows})
    print(f"over {N} projects: {colours} colours, {triples} arrangements, "
          f"{marks} marks with shape")

    # The fault, as a test. Projects that share a colour must not be forced to
    # share a mark; that is the whole reason the order moved to the grid.
    by_colour = {}
    for rgb, grid, _d in rows:
        by_colour.setdefault(text.hex_colour(rgb), []).append(grid)
    shared = [(c, gs) for c, gs in by_colour.items() if len(gs) > 1]
    collapsed = 0
    for _c, grids in shared:
        rgb = tuple(int(_c[i:i + 2], 16) for i in (1, 3, 5))
        if len({key(rgb, g) for g in grids}) < len(grids):
            collapsed += 1
    # Under the old rule every one of these collapsed by construction -- the
    # order and the shapes were a function of the colour, and the colour is what
    # these projects share. That is the comparison worth asserting, not a
    # threshold picked to pass.
    print(f"{len(shared)} colours carry more than one project; "
          f"{collapsed} still collapse to one mark, against "
          f"{len(shared)} under the old rule")
    assert collapsed < len(shared) / 2, (
        "projects sharing a colour are still sharing a mark")
    # What is left is the vocabulary running out, not the channel failing.

    # `draw_of` cannot be exact -- the colour is quantised -- and what matters
    # is whether the error crosses an arc.
    disagree = sum(1 for rgb, grid, draw in rows
                   if triple(rgb, grid) != triple(rgb, grid, draw))
    print(f"draw recovered from the colour alone: {disagree} of {N} "
          f"land in a different arc")
    print("selftest OK")


if __name__ == "__main__":
    _selftest()
