"""Layout for the system diagram: everything that is not semantic.

Generated once from the Python that used to hold the content as well,
then hand-maintained. `system-diagram.mr` is the source of what the
diagram says; this file is the source of where it goes.
"""

# page -> column widths, left to right
COLUMNS = {
    1: [376, 392, 376, 290],
    2: [376, 376, 376, 286],
    3: [396, 396, 396],
    4: [386, 376, 376, 356],
    5: [396, 376, 396, 366],
    6: [416, 386, 366, 350],
    7: [426, 426, 426],
    8: [660, 660],
    9: [426, 426, 426],
}

# page -> group heading -> column index
GROUPS = {
    1: {
        'WHAT APPLY READS': 0,
        'WHAT APPLY DERIVES, ON THE FIRST RUN': 1,
        'REDUCING IT TO ONE STRING': 2,
        'WHAT COMES OUT': 3,
    },
    2: {
        'THE DIGEST': 0,
        'THE MATRIX': 0,
        'THE COLOUR MAP': 1,
        'THE TRICOLOUR': 2,
    },
    3: {
        'NAMES': 0,
        'GEOMETRY': 1,
        'WHO USES THEM': 2,
    },
    4: {
        'WHAT ASKS FOR BYTES': 0,
        'PIXELS': 1,
        'CHARACTERS': 2,
        'THE SIBLING FILE': 3,
        'WHO ELSE RENDERS': 3,
    },
    5: {
        'WHAT ARRIVES': 0,
        'THE LATTICES': 1,
        'THE PALETTE': 2,
        'THE TRICOLOUR': 2,
        'READING ONE BACK': 3,
    },
    6: {
        'THE ONE ORCHESTRATOR': 0,
        'THE ASSETS': 1,
        'THE README LINE': 2,
        'ON DISK': 3,
    },
    7: {
        'THE RULE, APPLIED TO A RENDERING': 0,
        'THE FIVE THAT WENT NOWHERE': 1,
        'THE GAP IT LEFT': 2,
    },
    8: {
        'THE RULE THAT DECIDED IT': 0,
        'WHAT STAYED, AND WHY': 1,
    },
    9: {
        'THE CONTRACT': 0,
        "RUNNING SOMEBODY ELSE'S CODE": 1,
        'COMPARING IT': 2,
    },
}

# page -> hand-placed items: key -> (x, y, width)
PLACED = {
    0: {
        'main': (32, 40, 356),
        'argh': (32, 132, 356),
        'c_apply': (414, 40, 238),
        'c_show': (664, 40, 238),
        'c_render': (914, 40, 238),
        'c_validate': (1164, 40, 238),
        'c_doctor': (414, 162, 238),
        'm1': (32, 296, 340),
        'm2': (402, 296, 340),
        'm4': (772, 296, 340),
        'm3': (402, 436, 340),
        'm5': (772, 436, 340),
        'm6': (1142, 296, 386),
        'm7': (1142, 396, 386),
        'm8': (1142, 496, 386),
        'm9': (32, 496, 340),
    },
}

# (page, source, target, nth) -> routing for that edge
ROUTES = {
    (0, 'm1', 'm2', 0): {'sides': 'rl', 'wide': True},
    (0, 'm2', 'm4', 0): {'sides': 'rl', 'at': 0.34, 'bt': 0.34, 'wide': True},
    (0, 'm2', 'm4', 1): {'sides': 'rl', 'at': 0.72, 'bt': 0.72, 'wide': True},
    (0, 'm1', 'm3', 0): {'sides': 'bl', 'bt': 0.4, 'wide': True},
    (0, 'm4', 'm5', 0): {'sides': 'bt', 'wide': True},
    (0, 'm4', 'm6', 0): {'sides': 'rl', 'at': 0.35},
    (0, 'm4', 'm7', 0): {'sides': 'rl', 'at': 0.65, 'bt': 0.4, 'mid': 1120},
    (0, 'm1', 'm9', 0): {'sides': 'bt', 'at': 0.15, 'bt': 0.15},
    (1, 'r_apply', 'read_settings', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (1, 'read_settings', 'f_settings', 1): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (1, 'write_settings', 'f_settings', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (1, 'read_settings', 'identicon_seed', 0): {'sides': 'rr', 'at': 0.7, 'bt': 0.5, 'ext': 16},
    (1, 'derive_identicon_seed', 'repo_remote_url', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (1, 'repo_remote_url', '_git', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (1, '_git', 'p_git', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (1, 'derive_identicon_seed', 'extract_repository_name', 0): {'sides': 'rl', 'at': 0.3, 'bt': 0.45},
    (1, 'derive_identicon_seed', 'path_seed', 0): {'sides': 'tt', 'at': 0.9, 'bt': 0.3, 'ext': -16},
    (1, 'extract_repository_name', 'normalise_seed', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (1, 'path_seed', 'normalise_seed', 0): {'sides': 'rl', 'at': 0.7, 'bt': 0.7},
    (1, 'normalise_seed', 'v_seed', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3, 'wide': True},
    (1, 'v_seed', 'r_digest', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3, 'wide': True},
    (2, 'r_key', '_digest', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3, 'wide': True},
    (2, '_digest', 'identicon_grid', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3, 'wide': True},
    (2, '_digest', 'identicon_hue', 0): {'sides': 'bt', 'at': 0.7, 'bt': 0.7, 'wide': True},
    (2, 'identicon_hue', 'warp_hue', 0): {'sides': 'rl', 'bt': 0.4, 'wide': True},
    (2, 'warp_hue', 'gamut_chroma', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3, 'wide': True},
    (2, 'gamut_chroma', '_oklch_to_linear', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (2, '_oklch_to_linear', '_encode', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (2, 'gamut_chroma', 'identicon_colour', 0): {'sides': 'rl', 'at': 0.3, 'bt': 0.35, 'wide': True},
    (2, '_encode', 'identicon_colour', 0): {'sides': 'rl', 'bt': 0.8},
    (2, 'identicon_colour', 'UnknownMappingVersion', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (2, 'identicon_colour', '_colour_for', 0): {'sides': 'bt', 'at': 0.75, 'bt': 0.8},
    (2, 'identicon_grid', 'v_grid', 0): {'sides': 'rl', 'wide': True},
    (2, 'identicon_colour', 'v_colour', 0): {'sides': 'rl', 'at': 0.3, 'wide': True},
    (2, 'v_grid', 'grid_text', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3, 'wide': True},
    (2, 'v_colour', 'hex_colour', 0): {'sides': 'bt', 'at': 0.7, 'bt': 0.7, 'wide': True},
    (2, 'v_grid', 'r_rend', 0): {'sides': 'll', 'bt': 0.35, 'ext': 14},
    (2, 'v_colour', 'r_rend', 0): {'sides': 'll', 'bt': 0.65, 'ext': 22},
    (2, 'grid_text', 'r_art', 0): {'sides': 'bt', 'at': 0.8, 'bt': 0.35},
    (2, 'hex_colour', 'r_art', 0): {'sides': 'bt', 'bt': 0.6},
    (3, 'r_key3', 'short_hash', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3, 'wide': True},
    (3, 'short_hash', 'project_name', 0): {'sides': 'bt', 'at': 0.85, 'bt': 0.85},
    (3, 'project_name', 'badge_label', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (3, 'short_hash', 'icon_name', 0): {'sides': 'rr', 'at': 0.4, 'bt': 0.4, 'ext': 14},
    (4, 'r_emit4', 'render', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (4, 'render', 'resolve_colour_depth', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (4, 'resolve_colour_depth', 'resolve_protocol', 0): {'sides': 'bt', 'at': 0.85, 'bt': 0.85},
    (4, 'resolve_protocol', 'env', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (4, 'render', 'render_inline', 0): {'sides': 'rl', 'at': 0.35, 'bt': 0.3},
    (4, 'render_inline', 'iterm2_image', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (4, 'iterm2_image', 'kitty_image', 0): {'sides': 'bt', 'at': 0.85, 'bt': 0.85},
    (4, 'render_inline', 'render_png', 0): {'sides': 'bt', 'at': 0.85, 'bt': 0.85},
    (4, 'render_png', 'render_rgba', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (4, 'render_rgba', 'encode_png', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (4, 'render', 'render_ansi', 0): {'sides': 'rl', 'at': 0.55, 'bt': 0.35, 'mid': 833.0},
    (4, 'render', 'render_text', 0): {'sides': 'rl', 'at': 0.7, 'bt': 0.3, 'mid': 827.0},
    (4, 'render', 'render_banner', 0): {'sides': 'rl', 'at': 0.82, 'bt': 0.25, 'mid': 821.0},
    (4, 'render', 'render_line', 0): {'sides': 'rl', 'at': 0.94, 'bt': 0.2, 'mid': 815.0},
    (4, 'render_banner', 'render_text', 0): {'sides': 'll', 'at': 0.8, 'bt': 0.8, 'ext': 14},
    (4, 'render_banner', '_fg', 0): {'sides': 'rr', 'at': 0.75, 'bt': 0.3, 'ext': 14},
    (4, 'render_line', '_fg', 0): {'sides': 'rr', 'at': 0.75, 'bt': 0.7, 'ext': 22},
    (4, 'render_text', 'text_module_path', 0): {'sides': 'rl', 'at': 0.25, 'bt': 0.35, 'mid': 1235.0},
    (4, 'text_module_path', '_text_module', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (4, '_text_module', 'r_text5', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (4, 'render_line', 'r_emoji5', 0): {'sides': 'rl', 'at': 0.9, 'bt': 0.7, 'mid': 1241.0},
    (4, 'r_grid4', 'render_rgba', 0): {'sides': 'rl', 'at': 0.35, 'bt': 0.25, 'mid': 431.0},
    (4, 'r_grid4', 'render_svg', 0): {'sides': 'rl', 'at': 0.65, 'bt': 0.3, 'mid': 424.0},
    (4, 'r_bytes4', 'render_png', 0): {'sides': 'lr', 'bt': 0.7, 'mid': 1247.0},
    (5, 'r_rt', 't_text', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3, 'wide': True},
    (5, 't_text', 'grid_lines', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3, 'wide': True},
    (5, 'grid_lines', 'OCTANTS', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (5, 't_text', 'emoji_triple', 0): {'sides': 'rl', 'at': 0.75, 'wide': True},
    (5, 'emoji_triple', 'triple', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3, 'wide': True},
    (5, 'triple', 'triple_indices', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3, 'wide': True},
    (5, 'chosen_indices', 'nearest_colour', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (5, 'nearest_colour', '_mix', 0): {'sides': 'bt', 'at': 0.85, 'bt': 0.85},
    (5, 'triple', 'arrange', 0): {'sides': 'rl', 'at': 0.7, 'bt': 0.3, 'wide': True},
    (5, 'arrange', 'grid_bits', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3, 'wide': True},
    (5, '_mix', 'PALETTE', 0): {'sides': 'rl', 'bt': 0.4, 'mid': 843.0},
    (5, 'PALETTE', '_oklab', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (6, 'r_apply6', 'install_into_repo', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.2},
    (6, 'install_into_repo', 'install_json', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (6, 'install_json', 'r_ident6', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (6, 'install_into_repo', 'artifact_names', 0): {'sides': 'rl', 'at': 0.2, 'bt': 0.4},
    (6, 'artifact_names', 'artifact_paths', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (6, 'install_into_repo', 'artifact_bytes', 0): {'sides': 'rl', 'at': 0.45, 'bt': 0.3, 'mid': 461.0},
    (6, 'install_into_repo', 'r_keypath6', 0): {'sides': 'rl', 'at': 0.6, 'mid': 455.0},
    (6, 'install_into_repo', 'prior_path', 0): {'sides': 'rl', 'at': 0.75, 'bt': 0.3, 'mid': 449.0},
    (6, 'install_into_repo', 'readme_state', 0): {'sides': 'rl', 'at': 0.9},
    (6, 'readme_state', 'find_readme', 0): {'sides': 'll', 'at': 0.3, 'ext': 14},
    (6, 'readme_state', 'without_code_fences', 0): {'sides': 'll', 'ext': 22},
    (6, 'artifact_bytes', 'f_artifacts', 0): {'sides': 'rl', 'at': 0.3, 'bt': 0.12},
    (6, 'prior_path', 'f_artifacts', 0): {'sides': 'rl', 'bt': 0.3, 'mid': 1265.0},
    (6, 'r_keypath6', 'f_artifacts', 0): {'sides': 'rl', 'bt': 0.2, 'mid': 1258.0},
    (6, 'readme_state', 'f_readme', 0): {'sides': 'rl', 'at': 0.8},
    (6, 'artifact_bytes', 'r_rend6', 0): {'sides': 'rl', 'at': 0.9, 'bt': 0.4, 'mid': 881.0},
    (9, 'r_val9', 'vectors_path', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (9, 'vectors_path', 'load_vectors', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (9, 'load_vectors', 'f_vectors', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (9, 'f_vectors', 'r_parse9', 0): {'sides': 'bt', 'at': 0.8},
    (9, 'load_vectors', 'validate_command', 0): {'sides': 'rl', 'bt': 0.3},
    (9, 'validate_command', 'p_impl', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (9, 'validate_command', 'check_output', 0): {'sides': 'rl', 'bt': 0.3},
    (9, 'check_output', '_normalise_grid', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
    (9, '_normalise_grid', '_cell', 0): {'sides': 'bt', 'at': 0.3, 'bt': 0.3},
}

# page -> pixel width, where it is fixed rather than fitted
PAGE_WIDTH = {0: 1684, 1: 1576, 2: 1556, 3: 1400, 4: 1636, 5: 1676, 6: 1660, 7: 1400, 8: 1410, 9: 1400}
